### ISSUE TITLE
Option Icon and controller image

### ISSUE THREAD

**Issue by SuperSirLink** [semakusut/SBP-ROG-Ally#2]
noticed the options button shows the icon for what is the AC button, I was able rename the reference in the ally.css file. 
(just wondering if this by design)?

also not getting the controller image to show when viewing game controls, still show the PS controller image

**Comment by semakusut** [comment]
yaps i do that, to remember that the ac button is option for quicksettings haha

for the PS image, you should install hhd plugin, and change the controller to dualsense edge, when your m1 and m2 work

**Comment by SuperSirLink** [comment]
Yeah, I have that plugin install and set to edge, I do see the options for the buttons.  I have LED control turned off since I am using OpenRGB, would that impact displaying the controller image?

**Comment by semakusut** [comment]
it should work now, try to uninstall the css and reinstall it, sory, i edited it, its my fault lol, i miss the css bracket

**Comment by SuperSirLink** [comment]
Thanks! I will try that tonight, appreciate the assistance!

**Comment by semakusut** [comment]
your welcome sir

**Comment by SuperSirLink** [comment]
works! thanks!!

**Comment by semakusut** [comment]
glad its worked
